### ISSUE TITLE
better annotation

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2021#11]
how to go all in with all possible annotations...

**Comment by sr320** [comment]
can start with 09-11 nbs at https://github.com/RobertsLab/code

**Comment by kubu4** [comment]
Example notebook to use GFF (but, easily tweaked to use BLAST SPIDs as starting point) to retrieve UniProt data and parse out GO terms:

https://nbviewer.jupyter.org/github/RobertsLab/code/blob/master/notebooks/sam/20210601_ssal_gff-annotations.ipynb

Will require changing the mapping parameters in the Perl script (See `In [13]` in the notebook), per the [UniProt mapping guide](https://www.uniprot.org/help/api_idmapping).

**Comment by kubu4** [comment]
To add to my post above, Mac users may need to install some Perl modules (retrieving the UniProt data requires use of a Perl script). See [this Discussion on what might be needed](https://github.com/RobertsLab/resources/discussions/1227).

**Comment by kubu4** [comment]
Here's an example R script to use for mapping GO to GOslims (includes all three GOslim categories):

https://github.com/RobertsLab/code/blob/master/r_projects/sam/20200427_cbai_deg_go-goslims/scripts/GO_to_GOslim.R

Some tweaking that will be needed:

- Modify which files to work on (script is currently set to download a specific set of files).
- Modify parsing of input file. Script linked above is using output from GOseq.
- Modify output file naming/directory structures.
- Modify to include steps to download `goslim_generic.obo` from http://geneontology.org/docs/go-subset-guide/

EDITED: Hit enter by accident before content was added to post.
