### ISSUE TITLE
Figure out why Raven and Emu regularly die

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2021#16]

**Comment by kubu4** [comment]
Hmmm, Raven seems okay now. I've rebooted (remotely) a couple of times and haven't had any issues logging in (remotely). Not sure what was going on.

Still working on Emu...

**Comment by kubu4** [comment]
Well, Emu might be dunzo. The hardware lights do _not_ go through the normal progression when rebooting the machine. I've even physically unplugged it and started via the power button, but the normal hardware lights do not go through the expected progress. 

I'll do some internet sleuthing to see if I can find any other ideas.

**Comment by sr320** [comment]
Note Raven was off yesterday- I went into sr320 account and turned  off a couple of auto suspend settings.

**Comment by kubu4** [comment]
Off? Strange.

Regardless, looks like power save settings are screwing things up still. I'll dive into that junk a bit deeper.

**Comment by kubu4** [comment]
I think I have the Raven sleeping/hibernating thing resolved. I'll make a notebook entry about it.

**Comment by kubu4** [comment]
Emu has been declared dead. HDD/RAM have been removed. It's on cart for surplusing.
