### ISSUE TITLE
Update / correct Lab handbook 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2021#25]
via @drlawson 

**Simply Check off when addressed**

Notes for the lab handbook audit

- [x] On main page make sure everything starts with a capital letter because 80% does and 20% doesn’t, just makes it seem more organized
- [x] Double checked that all the links lead to the correct place

Lab culture 
Onboarding

- [x] SAFS undergrad resources for research, internships and study abroad does not work - find new link 
- [x] Research and internships: ​​https://fish.uw.edu/students/undergraduate-program/research-and-internships/, study abroad: https://fish.uw.edu/students/undergraduate-program/degree-overview-new/study-abroad/ 
- [x] Perhaps change the name of the “SAFS Graduate Students” link to “SAFS Graduate Program” because reading that I would think it was a link directly to the grad students - that is possible too but it’s a different link. Depends on what the purpose of that link should be 
- [ ] The “Graduate Program Adviser Amy Fox provides a link to Sam Scherer, maybe just take the link out and leave her email address 
- [x] “Postdoc Parenting Group” link just goes to Roberts lab notebook - change to http://depts.washington.edu/uwpa/who-we-are-2/ 
- [x] “UW College of the Environment Postdocs” link works but environment is misspelled
- [x] “SAFS postdoc channel on slack” just leads to SAFS community slack 

Code of Conduct

- [x] For “Title IX office” I wonder if we should link to https://www.washington.edu/titleix/ instead of the compliance and risk services website 
- [x] Q center has a new website: https://sites.uw.edu/qcenter 
- [x] UW health and wellness links to “Livewell,” should it link to this or did you want it to link to Husky health and well being? https://wellbeing.uw.edu/ 

Environment and Expectations

- [ ] Should we add “and respectfully” to the end of the first paragraph where it says “if you disagree with lab members you are encouraged to challenge them directly”?
- [x] In the “utmostly important” paragraph, I would suggest adding the word ‘these’ after the word “address”. 
- [x] Let's add a link to the book “getting things done” when you suggest it, perhaps https://gettingthingsdone.com/what-is-gtd/ 

Lab Communication looks good

Lab Notebooks looks good

DEI Resources

- [ ] UW health and wellness links to “Livewell” again, should  it link to this or did you want it to link to Husky health and well being? https://wellbeing.uw.edu/ 
- [ ] SAFS DEI slack link seems like it's just a link to SAFS community slack
- [ ] SAFS 360 is not a hyperlink - the link works but we should make it a hyperlink
- [ ] For the College of the Environment Community Equity Initiative: Organizational information TBA - maybe put this link: https://huskylink.washington.edu/organization/cei 
- [ ] The slack link listed for the college of the environment community equity initiative doesn’t work
- [ ] CoEnv diversity events link inactive and i can’t find one to replace it with 
- [ ] “Interrupting bias in academic settings” link does not exist - replace with https://ncwit.org/resource/biasacademic/ 

External Communication

- [ ] Link for no 2, pacific shellfish … takes you to an error page, replace with https://pcsga.org/ 
- [ ] Link for no 5 student travel award is just a link to special topics, can’t find a replacement link
- [ ] Lacking a traditional poster example
- [ ] “Students explore aquatic sciences (SEAS)” link needs to be changed to ​​ https://fish.uw.edu/alumni-community/students-explore-aquatic-sciences-seas/ 
- [ ] Add link to ocean inquiry project: http://www.oceaninquiry.org/about/ 
- [ ] Need new link for libbie hyman memorial scholarship, i can’t find a link to it on the website
- [ ] The nsf graduate research website link will be changing soon (beta available but it is not yet finalized - just keep your eye out for that)
- [ ] Can’t access the australia-americas PhD link without an account, maybe switch to this link? https://blogs.adelaide.edu.au/researchbulletin/2017/11/21/australian-academy-of-science-2018-australia-americas-phd-research-internship-program/ 

Lab Safety 

- [ ] “OARS” link did not work (at the bottom of the page) - change to https://oars.ehs.washington.edu/Oars/LoginUWashingtonShib 
- [ ] New hazardous waste website. Change to: https://webapps.ehs.washington.edu/chemwaste/index.php 

Covid plan 

- [ ] The link under “space” does not work 

Lab culture review complete

Computing and Code

Best Practices looks good (all links work)

Code snippets

- [ ] I am not sure what most of this means but if one understands code then it probably makes sense? I probably won’t be a huge help in the computing and code section 

Computing Hardware

- [ ] The links for github, slack, and roberts lab slack channels just take me to your lab notebook which my computer will not let me read 
- [ ] There is no information on the guide to using Jupyter notebooks
- [ ] The bottom link says “introduction to coding with python” but it should say “introduction to coding with R”
- [ ] 

Lab software
No comments because I don’t know what information is being presented here/anything about software

Mox New User

- [ ] No 4 under “designated technical contact” says “cluck” instead of “click”

Mox logging in looks good

If someone else could double check the rest of Mox guides that would be ideal because I have no idea what makes sense and what doesn’t. 

Databases and Catalogs

Lab Inventory

- [ ] -80C data sheet has missing “sample_type” for some samples. Should this get fixed?

Pubathon
Double checked the links for 2021 and they all work

DIgital Media looks good (all links work)

Experiment Database

- [ ] If needed/wanted we could have me try to compile more experiments into this datasheet so it gets closer to completion

Genomic Resources 

- [ ] Link under cbai_transcriptome_v2.0.fasta MD5 does not work (leads to 404 error page)
- [ ] Cbai_transcriptome_v1.6.fasta GO Terms Annotation (Trinotate) link doesn’t work 
- [ ] Got up to Crassostrea gigas - cgigas_uk_roslin_v1- do you need me to check all the links in this section? There seems to be hundreds haha. Just let me know what you think! 

Spotify playlists look good and work :)

 
 
Protocols
Purchasing and Reimbursement

- [ ] Under “procard”, the link to the training course should be changed to https://finance.uw.edu/ps/how-to-buy/procurement-card, a link to the procard section of the uw website instead of the general procurement section 
- [ ] I can’t access either the biochem or chem store catalogs - unsure if problem with the link or i just don’t have access
- [ ] We should add another link to lisa smith’s email under the personal purchases section just to make it easier 
- [ ] 

Data management

- [ ] Under NGS data management plan - backup, there is an extra question mark in the first bullet point after the word basis 
- [ ] Under SRA upload, SRA is written out as short read archive instead of sequence read archive (which is what it is called on the website)
- [ ] Under histology data management it mentions a unique-sample-ID but these are not present in the data sheet. Necessary?
- [ ] DOI link for Broman and Woo does not work (at the bottom of the sheet) - replace with this link https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989 

Lab protocols looks good

Chemical SOPs 

- [ ] Link for uw hazardous waste online collection has changed to  https://webapps.ehs.washington.edu/chemwaste/index.php 
- [ ] Link for RNAzol only takes you to the chemical sops page again. I’m not sure where it is supposed to take you 
- [ ] Same for the links of all the chemical names. Why are they hyperlinked?
- [ ] Safety GOOgles is written instead of goggles each time
- [ ] All the information is clearly presented

Alarm information 

- [ ] The phone numbers are unclear. Sam is missing a phone number on number 2 (unsure if that is purposeful), and then there is no name on number 3 in the list
- [ ] This section isn’t very clear. So there are 4 alarms correct? But only alarm 2 is talked about (the one that notifies you when power is cut off to freezer 1). Why are the other alarms listed above and not discussed? Unsure if this is necessary information but it seemed weird to just leave it out 

Bioinformatic workflows

Basics looks good - both videos play without an issue

DNA methylation analysis
No comments because I have never done this type of code so I am not sure what to look for

**Comment by sr320** [comment]
Example of how to tackle improvements
- Screen Recording https://d.pr/i/MjiTb7

attn: @drlawson 

edit:fixed link

**Comment by drlawson** [comment]
Onboarding line 90 (HR manager amy fox) - her email address is being mistaken for a hyperlink which takes you to an error page. can someone let me know how to change that so it registers that it is an email address instead of a link?

**Comment by sr320** [comment]
I fixed it. just removed the hyperlink 
now it looks like
`  - HR Mananger : Amy Fox (amyfox@uw.edu) `

**Comment by sr320** [comment]
@afcoyle @ocattau did you all not check off all of these - I thought Friday there were like 56 checked off?

**Comment by aspencoyle** [comment]
Huh, weird - yep we checked off almost all of them! 

As I remember, we were only missing the following:

-  The nsf graduate research website link will be changing soon (beta available but it is not yet finalized - just keep your eye out for that)

- [for Genomic Resources]  Got up to Crassostrea gigas - cgigas_uk_roslin_v1- do you need me to check all the links in this section? There seems to be hundreds haha. Just let me know what you think!
