### ISSUE TITLE
develop robust / universal blast notebook 

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hackweek-2021#5]
swiss-prot / GO

**Comment by kubu4** [comment]
Do you want this to include `makeblastdb` step or should that be assumed to have been completed?

**Comment by sr320** [comment]
I came up with this https://github.com/RobertsLab/code/blob/master/09-blast.ipynb

**Comment by kubu4** [comment]
I've begun working on an R Markdown notebook, as well:

https://github.com/RobertsLab/code/blob/master/script-box/complete_go_annotation_notebook.Rmd

It's not complete yet, but will be designed to:

- Get BLAST software and install.
- Download SwissProt BLAST database.
- Parse BLAST results to get SwissProt ID.
- Use SwissProt IDs to pull full SwissProt annotations.
- Parse out GO terms.
- Map GO terms to GOslims.
